/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Chat: typeof import('./src/components/chat.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Menu: typeof import('./src/components/menu.vue')['default']
    Menuvv: typeof import('./src/components/menuvv.vue')['default']
    Qrcode: typeof import('./src/components/qrcode.vue')['default']
    Text: typeof import('./src/components/text.vue')['default']
    Texti: typeof import('./src/components/texti.vue')['default']
  }
}
